// This file is generated by scripts/generate-calculator-catalog.ts.
// Do not edit it by hand. Update zdp-api-contracts/contracts/calculators/catalog.yaml instead.

import type { CalculatorErrorCode } from './index.js';

export interface CalculatorCatalogEntry {
  readonly id: string;
  readonly functionName: string;
  readonly lifecycleStatus: 'reviewed';
  readonly contractVersion: string;
  readonly compatibleEngineVersions: readonly string[];
  readonly requiredEngineVersion: string;
  readonly precisionPolicy: string;
  readonly roundingPolicy: string;
  readonly errorCodes: readonly CalculatorErrorCode[];
}

export const CALCULATORS = {
  'percentage-change': {
    id: 'percentage-change',
    functionName: 'calculatePercentageChange',
    lifecycleStatus: 'reviewed',
    contractVersion: '1.0.0',
    compatibleEngineVersions: [
      '0.x',
    ],
    requiredEngineVersion: '0.x',
    precisionPolicy: 'canonical_ascii_decimal_string_max_1000_digits',
    roundingPolicy: 'caller_decimal_places_0_to_100_half_away_from_zero',
    errorCodes: [
      'invalid_input',
      'domain_error',
      'limit_exceeded',
      'contract_mismatch',
      'denominator_zero',
      'precision_policy_required',
      'rounding_policy_required',
    ]
  },
  'margin-markup': {
    id: 'margin-markup',
    functionName: 'calculateMarginMarkup',
    lifecycleStatus: 'reviewed',
    contractVersion: '1.0.0',
    compatibleEngineVersions: [
      '0.x',
    ],
    requiredEngineVersion: '0.x',
    precisionPolicy: 'canonical_ascii_decimal_string_max_1000_digits',
    roundingPolicy: 'caller_decimal_places_0_to_100_half_away_from_zero',
    errorCodes: [
      'invalid_input',
      'domain_error',
      'limit_exceeded',
      'contract_mismatch',
      'denominator_zero',
      'incompatible_units',
      'precision_policy_required',
      'rounding_policy_required',
    ]
  },
  'break-even-point': {
    id: 'break-even-point',
    functionName: 'calculateBreakEvenPoint',
    lifecycleStatus: 'reviewed',
    contractVersion: '1.0.0',
    compatibleEngineVersions: [
      '0.x',
    ],
    requiredEngineVersion: '0.x',
    precisionPolicy: 'canonical_ascii_decimal_string_max_1000_digits',
    roundingPolicy: 'caller_decimal_places_0_to_100_half_away_from_zero',
    errorCodes: [
      'invalid_input',
      'domain_error',
      'limit_exceeded',
      'contract_mismatch',
      'non_positive_contribution_margin',
      'incompatible_units',
      'precision_policy_required',
      'rounding_policy_required',
    ]
  },
  'compound-interest': {
    id: 'compound-interest',
    functionName: 'calculateCompoundInterest',
    lifecycleStatus: 'reviewed',
    contractVersion: '1.0.0',
    compatibleEngineVersions: [
      '0.4.0',
      '0.5.0',
      '0.6.0',
    ],
    requiredEngineVersion: '0.6.0',
    precisionPolicy: 'canonical_ascii_decimal_string_max_1000_digits',
    roundingPolicy: 'caller_decimal_places_0_to_100_half_away_from_zero',
    errorCodes: [
      'invalid_input',
      'domain_error',
      'limit_exceeded',
      'contract_mismatch',
      'precision_policy_required',
      'rounding_policy_required',
    ]
  },
  'data-transfer-time': {
    id: 'data-transfer-time',
    functionName: 'calculateDataTransferTime',
    lifecycleStatus: 'reviewed',
    contractVersion: '1.0.0',
    compatibleEngineVersions: [
      '0.3.0',
      '0.4.0',
      '0.5.0',
      '0.6.0',
    ],
    requiredEngineVersion: '0.6.0',
    precisionPolicy: 'canonical_ascii_decimal_string_max_1000_digits',
    roundingPolicy: 'caller_decimal_places_0_to_100_half_away_from_zero',
    errorCodes: [
      'invalid_input',
      'domain_error',
      'limit_exceeded',
      'contract_mismatch',
      'unsupported_unit',
      'precision_policy_required',
      'rounding_policy_required',
    ]
  },
  'date-difference': {
    id: 'date-difference',
    functionName: 'calculateDateDifference',
    lifecycleStatus: 'reviewed',
    contractVersion: '1.0.0',
    compatibleEngineVersions: [
      '0.4.0',
      '0.5.0',
      '0.6.0',
    ],
    requiredEngineVersion: '0.6.0',
    precisionPolicy: 'exact_integer_calendar_days_years_0001_to_9999',
    roundingPolicy: 'not_applicable_exact_integer',
    errorCodes: [
      'invalid_input',
      'domain_error',
      'limit_exceeded',
      'contract_mismatch',
      'invalid_date_range',
    ]
  },
  'studycafe-seat-occupancy': {
    id: 'studycafe-seat-occupancy',
    functionName: 'calculateStudycafeSeatOccupancy',
    lifecycleStatus: 'reviewed',
    contractVersion: '1.0.0',
    compatibleEngineVersions: [
      '0.5.0',
    ],
    requiredEngineVersion: '0.5.0',
    precisionPolicy: 'canonical_ascii_decimal_string_max_1000_digits',
    roundingPolicy: 'caller_decimal_places_0_to_100_half_away_from_zero',
    errorCodes: [
      'invalid_input',
      'domain_error',
      'limit_exceeded',
      'contract_mismatch',
      'denominator_zero',
      'precision_policy_required',
      'rounding_policy_required',
    ]
  },
  'studycafe-break-even': {
    id: 'studycafe-break-even',
    functionName: 'calculateStudycafeBreakEven',
    lifecycleStatus: 'reviewed',
    contractVersion: '1.0.0',
    compatibleEngineVersions: [
      '0.5.0',
    ],
    requiredEngineVersion: '0.5.0',
    precisionPolicy: 'canonical_ascii_decimal_string_max_1000_digits',
    roundingPolicy: 'caller_decimal_places_0_to_100_half_away_from_zero',
    errorCodes: [
      'invalid_input',
      'domain_error',
      'limit_exceeded',
      'contract_mismatch',
      'denominator_zero',
      'incompatible_units',
      'precision_policy_required',
      'rounding_policy_required',
    ]
  },
  'kiosk-roi': {
    id: 'kiosk-roi',
    functionName: 'calculateKioskRoi',
    lifecycleStatus: 'reviewed',
    contractVersion: '1.0.0',
    compatibleEngineVersions: [
      '0.5.0',
    ],
    requiredEngineVersion: '0.5.0',
    precisionPolicy: 'canonical_ascii_decimal_string_max_1000_digits',
    roundingPolicy: 'caller_decimal_places_0_to_100_half_away_from_zero',
    errorCodes: [
      'invalid_input',
      'domain_error',
      'limit_exceeded',
      'contract_mismatch',
      'denominator_zero',
      'incompatible_units',
      'precision_policy_required',
      'rounding_policy_required',
    ]
  },
  'unattended-labor-savings': {
    id: 'unattended-labor-savings',
    functionName: 'calculateUnattendedLaborSavings',
    lifecycleStatus: 'reviewed',
    contractVersion: '1.0.0',
    compatibleEngineVersions: [
      '0.5.0',
    ],
    requiredEngineVersion: '0.5.0',
    precisionPolicy: 'canonical_ascii_decimal_string_max_1000_digits',
    roundingPolicy: 'caller_decimal_places_0_to_100_half_away_from_zero',
    errorCodes: [
      'invalid_input',
      'domain_error',
      'limit_exceeded',
      'contract_mismatch',
      'incompatible_units',
      'precision_policy_required',
      'rounding_policy_required',
    ]
  },
  'locker-revenue': {
    id: 'locker-revenue',
    functionName: 'calculateLockerRevenue',
    lifecycleStatus: 'reviewed',
    contractVersion: '1.0.0',
    compatibleEngineVersions: [
      '0.5.0',
    ],
    requiredEngineVersion: '0.5.0',
    precisionPolicy: 'canonical_ascii_decimal_string_max_1000_digits',
    roundingPolicy: 'caller_decimal_places_0_to_100_half_away_from_zero',
    errorCodes: [
      'invalid_input',
      'domain_error',
      'limit_exceeded',
      'contract_mismatch',
      'incompatible_units',
      'precision_policy_required',
      'rounding_policy_required',
    ]
  },
  'study-room-schedule-revenue': {
    id: 'study-room-schedule-revenue',
    functionName: 'calculateStudyRoomScheduleRevenue',
    lifecycleStatus: 'reviewed',
    contractVersion: '1.0.0',
    compatibleEngineVersions: [
      '0.5.0',
    ],
    requiredEngineVersion: '0.5.0',
    precisionPolicy: 'canonical_ascii_decimal_string_max_1000_digits',
    roundingPolicy: 'caller_decimal_places_0_to_100_half_away_from_zero',
    errorCodes: [
      'invalid_input',
      'domain_error',
      'limit_exceeded',
      'contract_mismatch',
      'incompatible_units',
      'precision_policy_required',
      'rounding_policy_required',
    ]
  },
  'security-cost-break-even': {
    id: 'security-cost-break-even',
    functionName: 'calculateSecurityCostBreakEven',
    lifecycleStatus: 'reviewed',
    contractVersion: '1.0.0',
    compatibleEngineVersions: [
      '0.5.0',
    ],
    requiredEngineVersion: '0.5.0',
    precisionPolicy: 'canonical_ascii_decimal_string_max_1000_digits',
    roundingPolicy: 'caller_decimal_places_0_to_100_half_away_from_zero',
    errorCodes: [
      'invalid_input',
      'domain_error',
      'limit_exceeded',
      'contract_mismatch',
      'non_positive_contribution_margin',
      'incompatible_units',
      'precision_policy_required',
      'rounding_policy_required',
    ]
  },
  'discount': {
    id: 'discount',
    functionName: 'calculateDiscount',
    lifecycleStatus: 'reviewed',
    contractVersion: '1.0.0',
    compatibleEngineVersions: [
      '0.x',
    ],
    requiredEngineVersion: '0.x',
    precisionPolicy: 'canonical_ascii_decimal_string_max_1000_digits',
    roundingPolicy: 'caller_decimal_places_0_to_100_half_away_from_zero',
    errorCodes: [
      'invalid_input',
      'domain_error',
      'limit_exceeded',
      'contract_mismatch',
      'precision_policy_required',
      'rounding_policy_required',
    ]
  },
  'age': {
    id: 'age',
    functionName: 'calculateAge',
    lifecycleStatus: 'reviewed',
    contractVersion: '1.0.0',
    compatibleEngineVersions: [
      '0.x',
    ],
    requiredEngineVersion: '0.x',
    precisionPolicy: 'exact_integer_calendar_days_years_0001_to_9999',
    roundingPolicy: 'not_applicable_exact_integer',
    errorCodes: [
      'invalid_input',
      'domain_error',
      'limit_exceeded',
      'contract_mismatch',
      'invalid_date_range',
    ]
  },
  'work-hours': {
    id: 'work-hours',
    functionName: 'calculateWorkHours',
    lifecycleStatus: 'reviewed',
    contractVersion: '1.0.0',
    compatibleEngineVersions: [
      '0.x',
    ],
    requiredEngineVersion: '0.x',
    precisionPolicy: 'canonical_ascii_decimal_string_max_1000_digits',
    roundingPolicy: 'caller_decimal_places_0_to_100_half_away_from_zero',
    errorCodes: [
      'invalid_input',
      'domain_error',
      'limit_exceeded',
      'contract_mismatch',
      'precision_policy_required',
      'rounding_policy_required',
    ]
  },
  'fuel-cost': {
    id: 'fuel-cost',
    functionName: 'calculateFuelCost',
    lifecycleStatus: 'reviewed',
    contractVersion: '1.0.0',
    compatibleEngineVersions: [
      '0.x',
    ],
    requiredEngineVersion: '0.x',
    precisionPolicy: 'canonical_ascii_decimal_string_max_1000_digits',
    roundingPolicy: 'caller_decimal_places_0_to_100_half_away_from_zero',
    errorCodes: [
      'invalid_input',
      'domain_error',
      'limit_exceeded',
      'contract_mismatch',
      'precision_policy_required',
      'rounding_policy_required',
    ]
  },
} as const satisfies Readonly<Record<string, CalculatorCatalogEntry>>;

export type CalculatorId = keyof typeof CALCULATORS;

export const CALCULATOR_IDS = Object.freeze(
  Object.keys(CALCULATORS) as CalculatorId[]
);

export const CALCULATOR_REQUIRED_ENGINE_VERSION = Object.freeze(
  Object.fromEntries(
    CALCULATOR_IDS.map((id) => [id, CALCULATORS[id].requiredEngineVersion])
  )
) as Readonly<Record<CalculatorId, string>>;
