import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repositoryRoot = fileURLToPath(new URL('..', import.meta.url));
const sourceFile = 'contracts/calculators/catalog.yaml';
const generatedHeader = `// This file is generated by scripts/generate-calculator-catalog.ts.
// Do not edit it by hand. Update zdp-api-contracts/contracts/calculators/catalog.yaml instead.`;

interface CalculatorDefinition {
  readonly id: string;
  readonly lifecycleStatus: 'reviewed';
  readonly contractVersion: string;
  readonly compatibleEngineVersions: readonly string[];
  readonly requiredEngineVersion: string;
  readonly precisionPolicy: string;
  readonly roundingPolicy: string;
  readonly errorCodes: readonly string[];
  readonly typeStem: string;
  readonly functionName: string;
}

const options = readOptions(process.argv.slice(2));
const sourcePath = join(options.apiContractsRoot, sourceFile);
const source = await readFile(sourcePath, 'utf8');
const definitions = parseReviewedDefinitions(source, sourcePath);
const outputs = [
  {
    path: join(repositoryRoot, 'src/calculator-engine/catalog.generated.ts'),
    content: renderCatalogModule(definitions)
  },
  {
    path: join(repositoryRoot, 'src/calculator-engine/registry.generated.ts'),
    content: renderRegistryModule(definitions)
  },
  {
    path: join(repositoryRoot, 'docs/generated/calculator-catalog.md'),
    content: renderCatalogDocument(definitions)
  }
] as const;

if (options.check) {
  const drifted = await findDriftedFiles(outputs);
  if (drifted.length > 0) {
    throw new Error(
      [
        'Generated calculator catalog files are stale:',
        ...drifted.map((path) => `- ${path}`),
        'Run `bun run calculator-catalog:generate` and commit the result.'
      ].join('\n')
    );
  }
  console.log(`Calculator catalog generation check passed for ${definitions.length} reviewed calculators.`);
} else {
  for (const output of outputs) {
    await mkdir(dirname(output.path), { recursive: true });
    await writeFile(output.path, output.content, 'utf8');
  }
  console.log(`Generated calculator catalog files for ${definitions.length} reviewed calculators.`);
}

function readOptions(argv: readonly string[]): {
  readonly apiContractsRoot: string;
  readonly check: boolean;
} {
  return {
    apiContractsRoot:
      readStringOption(argv, '--api-contracts-root') ??
      join(repositoryRoot, '..', 'zdp-api-contracts'),
    check: argv.includes('--check')
  };
}

function readStringOption(
  argv: readonly string[],
  optionName: string
): string | null {
  for (let index = 0; index < argv.length; index += 1) {
    if (argv[index] !== optionName) {
      continue;
    }

    const value = argv[index + 1];
    if (value === undefined || value.startsWith('--')) {
      throw new Error(`${optionName} requires a path.`);
    }
    return value;
  }

  return null;
}

function parseReviewedDefinitions(
  source: string,
  sourcePath: string
): readonly CalculatorDefinition[] {
  const parsed = Bun.YAML.parse(source) as unknown;
  if (!isRecord(parsed)) {
    throw new Error(`${sourcePath}: expected a YAML object.`);
  }

  const rawDefinitions = parsed.definitions;
  if (!Array.isArray(rawDefinitions)) {
    throw new Error(`${sourcePath}: expected a definitions array.`);
  }

  const definitions = rawDefinitions
    .filter(isRecord)
    .filter((definition) => definition.lifecycle_status === 'reviewed')
    .map((definition, index) => parseDefinition(definition, index, sourcePath));

  if (definitions.length === 0) {
    throw new Error(`${sourcePath}: expected at least one reviewed calculator.`);
  }

  assertUnique(
    definitions.map((definition) => definition.id),
    `${sourcePath}: calculator ids`
  );
  assertUnique(
    definitions.map((definition) => definition.typeStem),
    `${sourcePath}: generated TypeScript names`
  );

  return definitions;
}

function parseDefinition(
  definition: Record<string, unknown>,
  index: number,
  sourcePath: string
): CalculatorDefinition {
  const path = `${sourcePath}: definitions[${index}]`;
  const id = readString(definition, 'id', path);
  if (!/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(id)) {
    throw new Error(`${path}.id: expected a kebab-case calculator id.`);
  }

  const compatibleEngineVersions = readStringArray(
    definition,
    'compatible_engine_versions',
    path
  );
  const errorCodes = readStringArray(definition, 'error_codes', path);
  assertUnique(errorCodes, `${path}.error_codes`);

  const typeStem = toPascalCase(id);
  return {
    id,
    lifecycleStatus: 'reviewed',
    contractVersion: readString(definition, 'contract_version', path),
    compatibleEngineVersions,
    requiredEngineVersion:
      compatibleEngineVersions[compatibleEngineVersions.length - 1]!,
    precisionPolicy: readString(definition, 'precision_policy', path),
    roundingPolicy: readString(definition, 'rounding_policy', path),
    errorCodes,
    typeStem,
    functionName: `calculate${typeStem}`
  };
}

function readString(
  record: Record<string, unknown>,
  key: string,
  path: string
): string {
  const value = record[key];
  if (typeof value !== 'string' || value.trim().length === 0) {
    throw new Error(`${path}.${key}: expected a non-empty string.`);
  }
  return value.trim();
}

function readStringArray(
  record: Record<string, unknown>,
  key: string,
  path: string
): readonly string[] {
  const value = record[key];
  if (!Array.isArray(value) || value.length === 0) {
    throw new Error(`${path}.${key}: expected a non-empty string array.`);
  }

  return value.map((entry, index) => {
    if (typeof entry !== 'string' || entry.trim().length === 0) {
      throw new Error(`${path}.${key}[${index}]: expected a non-empty string.`);
    }
    return entry.trim();
  });
}

function assertUnique(values: readonly string[], label: string): void {
  const duplicate = values.find(
    (value, index) => values.indexOf(value) !== index
  );
  if (duplicate !== undefined) {
    throw new Error(`${label}: duplicate value \`${duplicate}\`.`);
  }
}

function toPascalCase(id: string): string {
  return id
    .split('-')
    .map((part) => `${part[0]!.toUpperCase()}${part.slice(1)}`)
    .join('');
}

function renderCatalogModule(
  definitions: readonly CalculatorDefinition[]
): string {
  const lines = [
    generatedHeader,
    '',
    "import type { CalculatorErrorCode } from './index.js';",
    '',
    'export interface CalculatorCatalogEntry {',
    '  readonly id: string;',
    '  readonly functionName: string;',
    "  readonly lifecycleStatus: 'reviewed';",
    '  readonly contractVersion: string;',
    '  readonly compatibleEngineVersions: readonly string[];',
    '  readonly requiredEngineVersion: string;',
    '  readonly precisionPolicy: string;',
    '  readonly roundingPolicy: string;',
    '  readonly errorCodes: readonly CalculatorErrorCode[];',
    '}',
    '',
    'export const CALCULATORS = {'
  ];

  for (const definition of definitions) {
    lines.push(
      `  ${quote(definition.id)}: {`,
      `    id: ${quote(definition.id)},`,
      `    functionName: ${quote(definition.functionName)},`,
      "    lifecycleStatus: 'reviewed',",
      `    contractVersion: ${quote(definition.contractVersion)},`,
      '    compatibleEngineVersions: ['
    );
    for (const version of definition.compatibleEngineVersions) {
      lines.push(`      ${quote(version)},`);
    }
    lines.push(
      '    ],',
      `    requiredEngineVersion: ${quote(definition.requiredEngineVersion)},`,
      `    precisionPolicy: ${quote(definition.precisionPolicy)},`,
      `    roundingPolicy: ${quote(definition.roundingPolicy)},`,
      '    errorCodes: ['
    );
    for (const errorCode of definition.errorCodes) {
      lines.push(`      ${quote(errorCode)},`);
    }
    lines.push('    ]', '  },');
  }

  lines.push(
    '} as const satisfies Readonly<Record<string, CalculatorCatalogEntry>>;',
    '',
    'export type CalculatorId = keyof typeof CALCULATORS;',
    '',
    'export const CALCULATOR_IDS = Object.freeze(',
    '  Object.keys(CALCULATORS) as CalculatorId[]',
    ');',
    '',
    'export const CALCULATOR_REQUIRED_ENGINE_VERSION = Object.freeze(',
    '  Object.fromEntries(',
    '    CALCULATOR_IDS.map((id) => [id, CALCULATORS[id].requiredEngineVersion])',
    '  )',
    ') as Readonly<Record<CalculatorId, string>>;',
    ''
  );

  return lines.join('\n');
}

function renderRegistryModule(
  definitions: readonly CalculatorDefinition[]
): string {
  const lines = [generatedHeader, '', 'import {'];
  for (const definition of definitions) {
    lines.push(`  ${definition.functionName},`);
  }
  lines.push("} from './index.js';", 'import type {');
  for (const typeName of [
    'CalculatorExecutionOptions',
    'CalculatorResult',
    'ExactIntegerExecutionOptions'
  ]) {
    lines.push(`  ${typeName},`);
  }
  for (const definition of definitions) {
    lines.push(
      `  ${definition.typeStem}Input,`,
      `  ${definition.typeStem}Output,`
    );
  }
  lines.push(
    "} from './index.js';",
    "import type { CalculatorId } from './catalog.generated.js';",
    '',
    'export interface CalculatorInputById {'
  );
  for (const definition of definitions) {
    lines.push(
      `  readonly ${quote(definition.id)}: ${definition.typeStem}Input;`
    );
  }
  lines.push('}', '', 'export interface CalculatorOutputById {');
  for (const definition of definitions) {
    lines.push(
      `  readonly ${quote(definition.id)}: ${definition.typeStem}Output;`
    );
  }
  lines.push('}', '', 'export interface CalculatorOptionsById {');
  for (const definition of definitions) {
    const optionsType =
      definition.roundingPolicy === 'not_applicable_exact_integer'
        ? 'ExactIntegerExecutionOptions'
        : 'CalculatorExecutionOptions';
    lines.push(`  readonly ${quote(definition.id)}: ${optionsType};`);
  }
  lines.push(
    '}',
    '',
    'type CalculatorExecutor = (',
    '  input: unknown,',
    '  options: unknown',
    ') => CalculatorResult<unknown>;',
    '',
    'const CALCULATOR_EXECUTORS = {'
  );
  for (const definition of definitions) {
    lines.push(`  ${quote(definition.id)}: ${definition.functionName},`);
  }
  lines.push(
    '} satisfies Readonly<Record<CalculatorId, CalculatorExecutor>>;',
    '',
    'export function calculateById<Id extends CalculatorId>(',
    '  id: Id,',
    '  input: CalculatorInputById[Id],',
    '  options: CalculatorOptionsById[Id]',
    '): CalculatorResult<CalculatorOutputById[Id]>;',
    'export function calculateById(',
    '  id: unknown,',
    '  input: unknown,',
    '  options: unknown',
    '): CalculatorResult<unknown> {',
    '  if (',
    "    typeof id !== 'string' ||",
    '    !Object.hasOwn(CALCULATOR_EXECUTORS, id)',
    '  ) {',
    '    return {',
    '      ok: false,',
    "      error: { code: 'invalid_input', field: 'calculator_id' }",
    '    };',
    '  }',
    '',
    '  return CALCULATOR_EXECUTORS[id as CalculatorId](input, options);',
    '}',
    ''
  );

  return lines.join('\n');
}

function renderCatalogDocument(
  definitions: readonly CalculatorDefinition[]
): string {
  const lines = [
    '# 계산기 카탈로그',
    '',
    '> 이 문서는 `zdp-api-contracts/contracts/calculators/catalog.yaml`에서 자동 생성된다. 직접 수정하지 않는다.',
    '',
    '| 계산기 ID | 함수 | 계약 | 호환 엔진 | 요구 엔진 | 오류 코드 |',
    '| --- | --- | --- | --- | --- | --- |'
  ];

  for (const definition of definitions) {
    const versions = definition.compatibleEngineVersions
      .map((version) => `\`${version}\``)
      .join(', ');
    const errorCodes = definition.errorCodes
      .map((errorCode) => `\`${errorCode}\``)
      .join(', ');
    lines.push(
      `| \`${definition.id}\` | \`${definition.functionName}\` | \`${definition.contractVersion}\` | ${versions} | \`${definition.requiredEngineVersion}\` | ${errorCodes} |`
    );
  }

  lines.push(
    '',
    '생성 명령은 `bun run calculator-catalog:generate`, 동기화 검사는 `bun run calculator-catalog:check`다.',
    ''
  );
  return lines.join('\n');
}

async function findDriftedFiles(
  outputs: readonly { readonly path: string; readonly content: string }[]
): Promise<readonly string[]> {
  const results = await Promise.all(
    outputs.map(async (output) => {
      try {
        return (await readFile(output.path, 'utf8')) === output.content
          ? null
          : output.path;
      } catch {
        return output.path;
      }
    })
  );
  return results.filter((path): path is string => path !== null);
}

function quote(value: string): string {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
